apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  gatewayClassName: cilium
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: argocd.manickam.local
      tls:
        mode: Terminate
        certificateRefs:
          - name: argocd-server-tls
            kind: Secret
            group: ''
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
    - name: argocd-gateway
      namespace: argocd
  hostnames:
    - argocd.manickam.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argocd-server
          port: 443
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-certificate
  namespace: argocd # This must match where your Gateway/ArgoCD live
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: argocd-server-tls # Cert-manager will create/update this secret
  dnsNames:
    - argocd.manickamx2.net
  issuerRef:
    name: cloudflare-dns01-issuer # Must match your ClusterIssuer name
    kind: ClusterIssuer # Crucial: tells cert-manager to look globally