apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/manickamx2/homelab.git'
      targetRevision: main
      ref: homelab
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.19.2
      helm:
        releaseName: cert-manager
        valueFiles:
          - $homelab/apps/cert-manager/values.yaml
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true