apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  sources:
    - chart: cert-manager
      repoUrl: https://charts.jetstack.io
      targetRevision: v1.19.2
      helm:
        releaseName: cert-manager
        valuesInline:
          installCRDs: true
          global:
            priorityClassName: "system-cluster-critical"
          replicas: 1
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true