apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ktQFn4GCOBdqR1VRaf40TKLwYf1oKgq/WHVpjiZpRt8blwtBi/zINwc2jsq+WUZ2hqCmwzNuakx/JZUS9h45hH3GMIN+0JCO2fszG6gbJgc69w==,iv:o1S7HezlcDPWABRYtfS0NXC1QpS6IvDSai5CbhO0biM=,tag:XJzjPkzrjTOsVIYJRSiKTg==,type:comment]
    #ENC[AES256_GCM,data:3f3H31XSQSf9CqCIPu88mM69F3rJwIL1mu/bnStvQr3uz1lsrR1Gw5rur1GYddyDUZxhQw==,iv:AnORXObZUZIWhM8StNcjDGtizij0cOs2hZdoxhkakIo=,tag:zUaLQDjWOoSb+6ba8s/8qQ==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:r21f2Y6MhT8+iEjDWcR+t5z/8ngqHrHOrC7hcLrmp91Fg2giwXpe/byWK2g=,iv:K00Azlw8kzwriGfoAy4RfzuX6Lzs8gFEBddTLVHCKnw=,tag:JjwtsyncJC/BIPnwAYTypA==,type:str]
sops:
    age:
        - recipient: age15zlz6uxh803uuvzxafga77l97t9gj5a4kfc9dk60vaks0xgamgasa6pnkf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTkVaTFhlU3lSME4rcDU0
            bDlJbWtYcnVVRjAyNzl3bjI0V0dRcUVMZGtrCnhUNmNjVXgwcFJVdEhaQk1vSUxO
            KzU2cEk5aFJjQUlGVjRKMmt3UTdSTFEKLS0tIEx3b1ZSRHo2cngzOEQxd1ZHUFpR
            K1BVdkZveFZMcmxvQjBucll2c01FUmsKYLwQm5/Y1OavpxKe8IhjdGTdwalOTyLe
            Tv88SYsWF0aWT2KkvSAQNGHiZzfE4tjh646NZmN9e+t6YuXJCP5bYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T00:11:02Z"
    mac: ENC[AES256_GCM,data:nPG5j4we5oYNHIqiNP0YrH9ugGCjOYCf47X2U/8FJWn9YH6NfJntkuMC3pNfv2KHIx3n5KJb231CBBMoJfnZUGT/BKTLh34CYqF4Lr6+aGVStys1f4FRGq9DnT5qEzzpPZ4IKutI4Xd3j1GHnvQKdaiUVShPjVof3ALcpFHcl30=,iv:Mv6FybnaZqDhp+5n3v2+V62fj63mAx97UDTkzPPGlk0=,tag:zDW6OXqF3NDRNw6pzN7mog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
