apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgresql
    namespace: authentik
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:MhXhRS7+IYGM/g==,iv:hnLncpRmSn1j7ccA8rP7sd4H21louS2CrWdxoq6cZ9g=,tag:3MEAZjntPK3XpOlFg0RU4w==,type:str]
    postgres-password: ENC[AES256_GCM,data:DefQIeXCuSjC2A==,iv:EdCeoHwB3/0sgBYlOfDxMp1KZvvcZtmHToFTICLlzLE=,tag:7kv9kgPYKx0NCSRR/Ixd7g==,type:str]
sops:
    age:
        - recipient: age15zlz6uxh803uuvzxafga77l97t9gj5a4kfc9dk60vaks0xgamgasa6pnkf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dEF4aGZaeUlHVGhvVzNL
            VWtFd2dhSEJWMXc1ekFXb1dnbmJhbG5ZVUZJCmUwYWN5amt1TWFEcnltK1lZcWVZ
            SUtvMXdVdDlNMkF0QWp6akZrODRFdFUKLS0tIHFpLzA4Q2tUUkpBOHNRMDZSVVFo
            WWM3SWVaYitGeVFHbE9malVTZWZLRjAKrn+jUCpr2mzOj9fGjg+lmI/T3kPpb9zH
            eothdWfvsujNJY7URBuzW1zOjgyK2t80EJGxKH54yufoaDa+SXWxfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T23:04:21Z"
    mac: ENC[AES256_GCM,data:q1Nltlb258M1qwZKdFEW1BQgpzzTonueXX9UGRH1Az0NZNZSskp9idcu55nkFFMRdsSYUTlHL3pqEnaTOmr5a0LSRBQaP6n8nDwG9xhWo0Veuf+9/aP88UqDWJDX9rjZmdsBmP8NrwG2EPubUUhYSVrWa7+uogHfL1QInlpz2z8=,iv:gEdgAqGt2unF7HLU/eZ6vZdEf3o1oyHZX3iqHHJrxA8=,tag:LrQYtP1NSsWTpC2B6nT72A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
