# Authentik Helm Chart Values
# https://github.com/goauthentik/helm/blob/main/charts/authentik/values.yaml

global:
  envFrom:
    - secretRef:
        name: "authentik-secret"

authentik:
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
    enabled: true

server:
  route:
    main:
      enabled: true
      hostnames:
        - authentik.manickamx2.com
      parentRefs:
        - name: public-gateway
          namespace: infrastructure

postgresql:
  enabled: true
