apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actual-budget

resources:
  - ./resources/deployment.yaml
  - ./resources/httproute.yaml
  - ./resources/pvc.yaml
  - ./resources/service.yaml
