apiVersion: v1
kind: Secret
metadata:
    name: minio-root-credentials
    namespace: minio
type: Opaque
stringData:
    root-user: ENC[AES256_GCM,data:2m2cC1hMj31fkcPm3C9dRwyK5/Ed9R9XnBnLQlHdhuRtvoM=,iv:Gtw5Q1ayVptHWA9QqVCM9GcVz2MIrYPeJ85DEr3mpso=,tag:V+6R2QhMgUGbjn1LfuC3RQ==,type:str]
    root-password: ENC[AES256_GCM,data:WvWrvz3+nTc3zqGilKt5OSKhGv0+H/nIdqcJimfr9DgzypgXwix4uZa6zPREM82MeVvE43l7dS+t0hmLA7ir/g==,iv:+xy0/n1PVl3hIY/iNDW1BUSaCCdD7TsiOvoTnJCROgk=,tag:qnzrKmrU0HwNX2EzOqKi7A==,type:str]
sops:
    age:
        - recipient: age15zlz6uxh803uuvzxafga77l97t9gj5a4kfc9dk60vaks0xgamgasa6pnkf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUTZCR1NPa3NMQk1xN0Ri
            N1ZrTWdvcThzeGVUSk15U0hCM1FZVkRKT1RjCjdxMDlhbVFhS1o1bU4wSFF4Nm5y
            VXh0M3pUYWkyZDlrQy9wVit4R1FLZFkKLS0tIHgyd3gyMVJqaWdHMisvNTZNM25l
            L0NvdjE3MDliNWk1cWNMMDgreFp4ck0K6XxyC6wjL0VcPCPH6t61UN5uPriHnw7z
            kPn0JfsqmFGbn04VPCJ52OMdxoaPOrywgotbW7GcGgKLJUVSxT6zug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T14:13:10Z"
    mac: ENC[AES256_GCM,data:FwDoAp6xjJcZpbC7eDm6fiHLr7fmfvPO8SVkd5rW/aq4kfqpqU9d8I1GolcCCpSJwgVJ6oFpzlno/29RhB46envvlhkk70aEsTCp41YfL9416Romyy4NLHe1q9yuujWU1mm3YiocejuyjkZUU0vfwM3N/O+zI93NFg0MzpWJMq0=,iv:YiIhW2wt1KRpnijmXzMRbeL151cN3lItlZ8a9AXU4i8=,tag:L2MgUictqTy1n+JAwz2jww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
