apiVersion: v1
kind: Secret
metadata:
    name: argocd-oidc-secret
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    oidc.authentik.clientSecret: ENC[AES256_GCM,data:X06lg/Auyjt5JIi5Ft+QT9kV41K6wv/NhpxENkrl9A9q7WH6taAZuWbyixF0EDehJpvTPGIswmuxeOoKbJLzDsRvBdkRooK+7rkag3HXDdThwx5iIuXER6hl5IXqg040LVJwzwXZtOIC6iPHoP6dlcFHgkAAotMWYrBHXVfgEEo=,iv:A+UAom1kjEqB4xAUTDKThheMrEKtH8Z9Bm0vJEgH0dw=,tag:Nn9mvdZ5gxuBI10j1hW6sg==,type:str]
sops:
    age:
        - recipient: age15zlz6uxh803uuvzxafga77l97t9gj5a4kfc9dk60vaks0xgamgasa6pnkf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM2VBVTE1elllWVBuNytZ
            WkhGZDh3bExxQktiUDVKUUtuUy83ZmFFMkJvCmZ1Z2tQNndqcmZydFdlWlg1OFZU
            TUdUV0JtSjFzVjk4NW8yZUVYLy9Db1UKLS0tIEhJRFNnZVJUQnVJdURjQkxyUVgy
            UnpvME5lemE2N3o0cWIrdXN5MWZRQ0EK/gpCF30fExfCobJo48CvVTe9zQNOURVy
            E3twH7NIZkmp3p2f3DqDJ8fGM1ibJcxRt2nGjhg+PSMUZLfkSxqp/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T04:43:42Z"
    mac: ENC[AES256_GCM,data:9rPbcuX0AvM99dpBOSWhJfvSf5zBnjdX52ThHxzIni67588o0LorEbPUQ63ftdgMvaVe/WKBVW9CoHei2H97Oa6T+mVYrn1TA3US9Agw6He5Zaooeoc7fFPAzvzxvh1kceMOI7adzUyUYbBqVDJ+TejXoiNlNkkQI/xrmVqUbic=,iv:l7Fk2CeyPig/YvAATyKyUqnNoDCndBxlyagxUs6Rdrw=,tag:i/ANgbJ8oRJ8kKm9hr/eJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
