apiVersion: v1
kind: Secret
metadata:
    name: argocd-oidc-secret
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    oidc.authentik.clientSecret: ENC[AES256_GCM,data:FCaMJ4UMVToDrDqgfm8GZvUbQLY6TjZzwD0xtHFgcHmAgfSQn8wBu3Ntnq+IJqTBwBqAFtmW34xnhCNMZcoG4tKSQ9XD/etJIV2DHmnz8ztzIEC778WkW6JCCizbDAEEI4UuV3Ul68B7SDdeIwaLqs5Cp0FWbHe4U6DmAm0MC9c=,iv:0+u1Hdd7xC8gBvQUK1nhiMO9fz7jwSrIojndj6tmeMc=,tag:wt25qvXX2SIzE5kEQHN3Rg==,type:str]
sops:
    age:
        - recipient: age15zlz6uxh803uuvzxafga77l97t9gj5a4kfc9dk60vaks0xgamgasa6pnkf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZTYyeElrT2k4NGtacXM0
            WENUSkZyaDJ0SlF4MHBwcEg5Vkc0N0p6cUdFCjRSN1FxR3BHZlE4Y3IwVEZXQldj
            MklqMm1ORHBkOVpXTEIyRGhBaVNGdFUKLS0tIHBDbXUvWDNxdzcxWWxDQ3pkYXlB
            NjIzcjRqY2hudXBtVUViOG5scjE0NE0KlKbGxvY5TX7e2wwjnkg4DR2/Qau4lWu+
            AKeBRORGCjCrgkVeQm/ZrDmQ35YnDMIBcW46n+8Y7lw0nH91Kd9H0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T04:29:14Z"
    mac: ENC[AES256_GCM,data:NdUSz0qguvTOLF2YMXqzWcesBCbm2CAZB4WWLrjNJ2hls7WfFzWx7bWZ1A6AkoT6Ga+XiEaQyxgpemIcFWHtmGKHXFvyHfnPkjoZBD41qXRL++C1PzI4g8dmKVD7tRTMvz6A0Q02aZCIXqT5dHscIEVVVPdtEA+xhPQNXNaHQ70=,iv:CgKs/1bu8zR5uksQ9BHp0hMi9atC13hxwHRt06aRUSE=,tag:47gpOBBdBbNV7ebAorrVtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
